name: run-tests

on:
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true


jobs:
  handle-syncwith:
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@v1.1.2
    with:
      ci-cd-ref: 'v1.1.2'
    secrets: inherit


  run-tests:
    runs-on: [ ubuntu-22.04 ]
    needs:
      - handle-syncwith
    steps:
      - uses: actions/checkout@v3

      - name: Checkout modules to specified refs
        if: needs.handle-syncwith.outputs.prs-refs != ''
        uses: NilFoundation/ci-cd/actions/recursive-checkout@v1.1.2
        with:
          paths: |
            ${{ github.workspace }}/**
            !${{ github.workspace }}/**/.git/**
          refs: ${{ needs.handle-syncwith.outputs.prs-refs }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: Install node dependencies
        run: |
          export UV_USE_IO_URING=0
          npm install

      - name: Hadrhat tests
        run: |
          npx hardhat test

      - name: Hadrhat deploy
        run: |
          npx hardhat deploy

      - name: Verification of all zkllvm proofs
        run: |
          npx hardhat verify-circuit-proof-all
