name: run-tests

on:
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true


jobs:
  run-tests:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: Install node dependencies
        run: |
          npm install

      - name: Hadrhat tests
        run: |
          npx hardhat test

      - name: Hadrhat deploy
        run: |
          npx hardhat deploy
      
      - name: Verification of all zkllvm proofs
        run: |
          npx hardhat verify-circuit-proof-all
